### ISSUE TITLE
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir' 

### ISSUE THREAD

**Issue by JarbasAl** [forslund/combo-lock#19]
originally reported in https://github.com/OpenVoiceOS/ovos-messagebus/issues/12

**Comment by forslund** [comment]
I've created a mac-os-x runner and a testcase that exercises the issue in the branch (mac-os) See [job 73](https://github.com/forslund/combo-lock/actions/runs/5098172541/jobs/9165158396)

**Comment by goldyfruit** [comment]
Awesome! 👍
