### ISSUE TITLE
NamedLock name could cause FileNotFoundError

### ISSUE THREAD

**Issue by NeonDaniel** [forslund/combo-lock#5]
**Describe the bug**
If something like a file path is passed to `NamedLock`, a FileNotFoundError is raised

**To Reproduce**
```python
lock = NamedLock('this/is/my/lock/name`)
```

**Expected behavior**
Lock should be created with a cleaned name (i.e.: https://github.com/NeonGeckoCom/neon-skill-utils/blob/ef8f9bbf245cb79733ebdabc9eae889c67c4ff97/neon_utils/parse_utils.py#L73)

**Comment by forslund** [comment]
Thanks for opening this issue and proposing a solution... Do you think it would be an issue with the cleaning duplicating a lock name?

`NamedLock('this/Is/My/Lock')` would be the same lock as `NamedLock('this_Is_My_Lock)`. We could do a hash of the input name and use that to get a unique lock file for each name even if it contains weird characters?

**Comment by JarbasAl** [comment]
why not create the paths instead? ensures uniqueness and seems to be what the user intended
