### ISSUE TITLE
Multiple instances all acquire file lock

### ISSUE THREAD

**Issue by NeonDaniel** [forslund/combo-lock#7]
**Describe the bug**
If multiple `ComboLock` or `NamedLock` instances are created in separate threads, they will all acquire a file lock

**To Reproduce**
Test case can be found here https://github.com/NeonDaniel/combo-lock/blob/e294c50efc11c07497e564ab4171a62eb623ae7c/tests/test_lock.py#L61-L75

**Expected behavior**
All instances of `ComboLock` with the same file should lock using that file

**Environment (please complete the following information):**
 - Device type: x64
 - OS: Linux Mint/Ubuntu
 - Other versions: fasteners 0.16.3

**Comment by NeonDaniel** [comment]
`filelock.FileLock` appears to provide the expected functionality based on my testing; this package appears to be a drop-in replacement

**Comment by forslund** [comment]
Hmm, the testcase doesn't really work, the lock needs to be shared between the threads to work, otherwise each will have their own thread-lock. The way the combo-lock is constructed, the lock needs to be shared between the threads. Like a standard thread lock.

The test case should look something like

```python
    def test_multi_lock_acquire(self):
        results = dict()
        lock = ComboLock(self.lock_file)

        def _test_acquire(idx):
            success = lock.acquire(False)
            results[idx] = success

        for i in range(0, 10):
            Thread(target=_test_acquire, args=(i,), daemon=True).start()

        while not len(results.keys()) == 10:
            time.sleep(0.5)
        self.assertEqual(len([lock for lock in results.values() if lock]), 1)
```

The file lock would make the thread part of the _combolock_ completely redundant, the idea of the lock is that the IPC lock from fasteners would be faster than the one _filelock_ but I need to measure that to make sure it's still true.

**Comment by forslund** [comment]
Did some tests and using the filelock straight up is faster. So it's a better tool than combo_lock and should probably be used instead of the combo lock.

**Comment by NeonDaniel** [comment]
I see, that makes sense then.. I thought the plock was essentially equivalent to a file lock, but that would render the thread lock redundant.. Would it make sense to add a file lock to this package? The RAM disk and filename utils are still applicable there

**Comment by forslund** [comment]
Yes, the processlock was sort of equivalent but it's not blocking for calls from other threads in the same process, hence the thread lock (and the resulting combination of a process lock and a thread lock -> combolock).

Seems like the filelock does both things and even is a bit faster so right now I would recommend to use the filelock straight up.

The combolock may have some extra conveniences and the autonaming provided by the NamedLock, wich are good. Maybe we can do a final release of this as a wrapper around the filelock and then propose upstream changes to filelock?

**Comment by NeonDaniel** [comment]
I think the thread lock is still useful with FileLock to allow one lock instance to be shared between threads (at least, that's how I implemented it [in neon-utils](https://github.com/NeonGeckoCom/neon-skill-utils/blob/40f8ec654445cf8f09580c79f4a756fe6a08f382/neon_utils/lock_utils.py#L32)).

Filelock will let the same lock acquire multiple times across threads (from https://github.com/tox-dev/py-filelock):
```
The lock objects are recursive locks, which means that once acquired, they will not block on successive lock requests
```
So, Filelock isn't quite a drop-in replacement for combo-lock. I think any actual use case can get by with FileLock alone, but adding a thread lock makes it a little easier to manage since you don't need a lock instance per thread (and this would maintain Combolock backwards-compatibility)..

**Comment by forslund** [comment]
You have a point here
