### ISSUE TITLE
Allow loose dep requirements or support the latest filelock

### ISSUE THREAD

**Issue by PureTryOut** [forslund/combo-lock#9]
Currently this library requires filelock 3.2.x, while upstream already has 3.3.2 available. In Alpine Linux we (will) ship 3.3.2 and 3.2.0 is not something we can provide.

**Comment by NeonDaniel** [comment]
I think this was from my PR; only reason it was locked to 3.2.x is that it was the latest available at the time. Perhaps this should just be `filelock~=3.2`?

**Comment by PureTryOut** [comment]
That still wouldn't make it work with 3.3 afaik, so no 😛

**Comment by forslund** [comment]
I believe `filelock~=3.2` should work (versions compatible with 3.2). It's basically expanded to `>=3.2 and ==3.*` if I've understood it correctly

**Comment by NeonDaniel** [comment]
> I believe `filelock~=3.2` should work (versions compatible with 3.2). It's basically expanded to `>=3.2 and ==3.*` if I've understood it correctly

This was my understanding.. This way (if filelock follows semantic versioning), we get any non-breaking changes

**Comment by forslund** [comment]
I looked at the history and they seem to be using semantic versioning, though one persons bugfix is anothers breaking change so it won't guarantee correctness but it will at least hint at it

**Comment by forslund** [comment]
v0.2.1 has been published which has looser requirements for filelock and should work with the Alpine release. Closing this issue.
